version: 2
jobs:
  build:
    working_directory: ~/simple-node-js
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
